% placeRoiCuboids - Place initial ROI cuboids on a point cloud
%
% Description:
% ------------
%       Can only be called from dynAnalyis with a prior call to
%       placeObjCuboid.
%
% Input Arguments:
% ----------------
%       f1 - figure
%           Figure where the point cloud and bounding box are visible
%       objCuboid - cuboid
%           Instance of the bounding box of this point cloud frame
%
%   Output Arguments
%   ----------------
%       roiCuboids - array of cuboids
%           Array containing the first four Z-analyis ROI cuboids on the
%           left step S1-S2 of this point cloud frame. Plus the ROI cuboid
%           of the X-Y-analysis on left step S1.

function roiCuboids = placeRoiCuboids(f1, objCuboid, boxOrientation)
    load('StaircaseData.mat', ...
        'objDim','stepWidth', 'stepLength');

    if strcmp(boxOrientation, 'Horizontal')
        xTemp = objDim.x;
        objDim.x = objDim.y;
        objDim.y = xTemp;
    end

    axes = f1.CurrentAxes;

    % Z-Analysis
    if strcmp(boxOrientation, 'Vertical')
        roiCuboids.z(1) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + stepWidth/4, ...
            objCuboid.Position(2) - stepLength/2, ...
            objCuboid.Position(3) - objDim.z*8, ...
            objDim.x/4, stepLength, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '1', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(2) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + stepWidth/2, ...
            objCuboid.Position(2) + stepLength/4, ...
            objCuboid.Position(3) - objDim.z*8, ...
            objDim.x/2, stepLength/2, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '2', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(3) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + stepWidth/4, ...
            objCuboid.Position(2) + stepLength/2, ...
            objCuboid.Position(3) - objDim.z*8, ...
            objDim.x/4, stepLength, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '3', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(4) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) - stepWidth/2, ...
            objCuboid.Position(2) + stepLength/4, ...
            objCuboid.Position(3) - objDim.z*8, ...
            objDim.x/2, stepLength/2, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '4', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
    else
        roiCuboids.z(1) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + objCuboid.Position(4) - stepLength/2, ...
            objCuboid.Position(2) + stepWidth/4, ...
            objCuboid.Position(3) - objDim.z*8, ...
            stepLength, objDim.y/4, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '1', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(2) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + objCuboid.Position(4) - (3*stepLength)/4, ...
            objCuboid.Position(2) + stepWidth/2, ...
            objCuboid.Position(3) - objDim.z*8, ...
            stepLength/2, objDim.y/2, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '2', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(3) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + objCuboid.Position(4) - (3*stepLength)/2, ...
            objCuboid.Position(2) + stepWidth/4, ...
            objCuboid.Position(3) - objDim.z*8, ...
            stepLength, objDim.y/4, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '3', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
        roiCuboids.z(4) = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + objCuboid.Position(4) - (3*stepLength)/4, ...
            objCuboid.Position(2) - stepWidth/2, ...
            objCuboid.Position(3) - objDim.z*8, ...
            stepLength/2, objDim.y/2, objDim.z*16], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '4', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
    end

    % XY-Analysis
    if strcmp(boxOrientation, 'Vertical')
        roiCuboids.xy = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + stepWidth/4, ...
            objCuboid.Position(2) + stepLength/4, ...
            objCuboid.Position(3) - objDim.z/16, ...
            stepWidth/2, stepLength/2, objDim.z/8], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '1', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
    else
        roiCuboids.xy = drawcuboid(axes, 'Color', 'red', ...
            'Position', [objCuboid.Position(1) + objCuboid.Position(4) - (3*stepLength)/4, ...
            objCuboid.Position(2) + stepWidth/4, ...
            objCuboid.Position(3) - objDim.z/16, ...
            stepLength/2, stepWidth/2, objDim.z/8], ...
            'InteractionsAllowed', 'none', ...
            'Selected', 0, 'Label', '1', ...
            'EdgeAlpha', 0.2, 'FaceAlpha', 0.1, 'LabelAlpha', 0.2);
    end

end

